### ISSUE TITLE
update copyright information in index.php and other files

### ISSUE THREAD

**Issue by ttoine** [friends-of-presta/fop_customcss#8]
In this file
https://github.com/friends-of-presta/fop_customcss/blob/master/index.php

The copyright information is just a copy paste of the one from the PrestaShop SA company. It must be updated with Friend of Presta copyright information.

Also, I see that the license.md file include the MIT license, and that in the index.php file, the AFL is specified. So, this is not coherent.

**Comment by SebSept** [comment]
So, we can use the text written in prestashop files and change Prestashop S.A by Friends of Presta ?
On each file ? or only on files created for the projet ?

**Comment by ttoine** [comment]
such information should on each file created by the project.
however you must not change files from libraries and dependencies, or files you tool from an other module (if any)
